##1. importo libreria

In [2]:

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

##2.Cargar dataset

In [10]:
df = pd.read_csv('usuarios_win_mac_lin (1).csv')

print("--- VISTA PREVIA DEL DATASET ---")
print(df.head())

--- VISTA PREVIA DEL DATASET ---
   duracion  paginas  acciones  valor  clase
0       7.0        2         4      8      2
1      21.0        2         6      6      2
2      57.0        2         4      4      2
3     101.0        3         6     12      2
4     109.0        2         6     12      2


##3.Separar variables y dividir en entrenamiento/prueba

In [5]:
X = df.iloc[:, :4].values
y = df.iloc[:, 4].values

X_train, X_test, y_train, y_test = model_selection.train_test_split(
    X, y, test_size=0.20, random_state=42
)

##4.Crear y entrenar el modelo

In [6]:
clasificador = linear_model.LogisticRegression(solver='lbfgs', max_iter=1000)
clasificador.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

##5.Predecir sobre conjuto de prueba

In [7]:
y_pred = clasificador.predict(X_test)

##6.evaluar modelo

In [8]:
print("\n--- RESULTADOS DE EVALUACIÓN ---")
print("Exactitud (Accuracy):", round(accuracy_score(y_test, y_pred), 4))

print("\n--- MATRIZ DE CONFUSIÓN ---")
print(confusion_matrix(y_test, y_pred))

print("\n--- REPORTE DE CLASIFICACIÓN ---")
print(classification_report(y_test, y_pred, target_names=['Windows', 'Macintosh', 'Linux']))


--- RESULTADOS DE EVALUACIÓN ---
Exactitud (Accuracy): 0.6765

--- MATRIZ DE CONFUSIÓN ---
[[13  2  1]
 [ 8  4  0]
 [ 0  0  6]]

--- REPORTE DE CLASIFICACIÓN ---
              precision    recall  f1-score   support

     Windows       0.62      0.81      0.70        16
   Macintosh       0.67      0.33      0.44        12
       Linux       0.86      1.00      0.92         6

    accuracy                           0.68        34
   macro avg       0.71      0.72      0.69        34
weighted avg       0.68      0.68      0.65        34



##7. predecir un nuevo usuario

In [9]:
nuevo_usuario = np.array([[120, 5, 18, 35]])
prediccion = clasificador.predict(nuevo_usuario)

sistemas = {0: 'Windows', 1: 'Macintosh', 2: 'Linux'}
print(f"\nEl sistema operativo predicho es: {sistemas[prediccion[0]]}")


El sistema operativo predicho es: Windows
